---
#TO DO
#Re-learn how to run ONLY if a previous condition has been met
#Begin creating snippet folder so we don't have to look shit up over and over

- name: Install Platform Software
  hosts: platform
  remote_user: root
  roles:
    - install
 
- name: Configure Platform Software
  hosts: platform
  remote_user: root
  roles:
    - configure
