---
- name: Configure | Adding configuration files
  # copy FROM ansible controller to target machine (fetch is the opposite)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    #mode: 0644
    backup: yes
  # more complex iteration: each item now has src: and dest: attributes
  with_items:
    - src: "global_nginx"
      dest: "/etc/nginx/nginx.conf"
      #- src: "config/mywebsite.conf"
      #dest: "/etc/nginx/conf.d/mywebsite.conf"

- name: Configure | Creating cache directory
  file: path=/usr/share/nginx/cache/fcgi  state=directory

- name: Configure | Testing nginx.conf 
  raw: nginx -t
      #	4. Test the new nginx.conf file
      #		- nginx -t
      #
      #29. Basic php-fpm Configuration
      #
      #1. Install the PHP extentions we need for wordpress
      #- apt-get update
      #- apt-get install php-json php-xmlrpc php-curl php-gd php-xml php-mbstring
      #
      #2. Make the directory for php-fpm sockets
      #- mkdir /var/run/php-fpm
      #
      #3. Make sure /etc/php/7.1/fpm/pool.d exists
      #
      #4. Backup the php-fpm.conf file
      #- cd /etc/php/7.1/fpm/
      #- cp php-fpm.conf php-fpm.conf.ORIG
      #
      #5. Clear the .conf file
      #- echo "" > php-fpm.conf
      #
      #6. Insert text from the following file into php-fpm.conf 
      #- ~/git_repos/hosting_platform/config_files/global_php-fpm.conf
      #
      #7. Remove the original (default) pool:
      #- rm /etc/php/7.1/fpm/pool.d/www.conf
      #
      #8. Backup php.ini
      #- cd /etc/php/7.1/fpm
      #- mv php.ini php.ini.ORIG
      #
      #9. Insert text from the following file into php.ini
      #- ~/git_repos/hosting_platform/config_files/php.ini
      #
      #*** Restart php7.1-fpm after adding future config file ***
      #- systemctl restart php7.1-fpm
      #
      ##
